<h2>Blog With Author Detail</h2>

<table style="border:1px solid black;text-align:center">
    <tr>
        <th colspan="7" style="border:1px solid black;text-align:center">Blog</th>
        <th colspan="3" style="border:1px solid black;text-align:center;vertical-align:middle">Author</th>
    </tr>

    <tr>
        <td style="border:1px solid black;">Title</td>
        <td style="border:1px solid black;">Description</td>
        <td style="border:1px solid black;">Content</td>
        <td style="border:1px solid black;">URL_rewrite</td>
        <td style="border:1px solid black;">Status</td>
        <td style="border:1px solid black;">Create_at</td>
        <td style="border:1px solid black;">Update_at</td>
        <td style="border:1px solid black;">Firstname</td>
        <td style="border:1px solid black;">Lastname</td>
        <td style="border:1px solid black;">Email</td>
    </tr>
    
<?php foreach ($block->getBlogWithAuthorById() as $blog): ?>
    <tr>
        <td style="border:1px solid black;"><?php echo $blog->getTitle() ?></td>
        <td style="border:1px solid black;"><?php echo $blog->getDescription() ?></td>
        <td style="border:1px solid black;"><?php echo $blog->getContent() ?></td>
        <td style="border:1px solid black;"><?php echo $blog->getUrlRewrite() ?></td>
        <td style="border:1px solid black;"><?php echo $blog->getStatus() ?></td>
        <td style="border:1px solid black;"><?php echo $blog->getCreateAt() ?></td>
        <td style="border:1px solid black;"><?php echo $blog->getUpdateAt() ?></td>
        <td style="border:1px solid black;"><?php echo $blog->getFirstname() ?></td>
        <td style="border:1px solid black;"><?php echo $blog->getLastname() ?></td>
        <td style="border:1px solid black;"><?php echo $blog->getEmail() ?></td>
    </tr>
<?php endforeach; ?>

</table>