<table>
    <tr>
        <th><button id="alert-modal" class="swatch-option">Open Modal</button></th>
        <th><button class="swatch-option">Open Magento Login Modal</button></th>
        <th><button class="swatch-option">Open Custom Login Modal</button></th>
    </tr>
</table>

<!-- <script>
    define(
    'jquery'
    , function() {
        $("#alert-modal").click(function(){
            alert("Ok");
        })
        return window.jQuery 
    }
)
</script> -->